import type { ActProvision, Bill, ProvisionDelta } from "../types";

const esc = (s: string) =>
  (s ?? "").replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[c] as string);

type Step = { kind: string; label: string };

// Hierarchy steps — prefer the server `path`, else derive from the composed label.
function segments(p: ActProvision): Step[] {
  if (p.path && p.path.length) return p.path;
  const label = p.label ?? "";
  if (/^[“"']/.test(label)) return [{ kind: "definition", label }];
  const sec = label.match(/^([0-9]+(?:\.[0-9]+)*[A-Za-z]?)/);
  const out: Step[] = [];
  let rest = label;
  if (sec) { out.push({ kind: "section", label: sec[1] }); rest = label.slice(sec[1].length); }
  for (const g of rest.match(/\([^)]+\)/g) ?? []) out.push({ kind: "sub", label: g.replace(/[()]/g, "") });
  return out.length ? out : [{ kind: "section", label }];
}

// Leaf label as it reads in a statute: "5.3", a quoted term, or "(c)".
function leaf(p: ActProvision): string {
  if (p.kind === "schedule") return p.label;
  const segs = segments(p);
  const last = segs[segs.length - 1];
  if (!last) return p.label;
  return last.kind === "section" || last.kind === "definition" ? last.label : `(${last.label})`;
}

// Branded, print-ready rendering of the amended Act: the after-side of the delta
// (skip repealed, keep document order), amended provisions subtly marked. Opens a
// print window — the browser's "Save as PDF" produces the file. Returns false if
// the pop-up was blocked. One call = one Act = one PDF.
export function exportActAsPdf(delta: ProvisionDelta, bill: Bill | null): boolean {
  const body = delta.rows
    .filter((r) => r.status !== "repealed")
    .map((r) => {
      const p = r.after ?? r.before;
      if (!p) return "";
      const depth = Math.max(0, segments(p).length - 1);
      const amended = r.status === "added" || r.status === "changed";
      const mn = p.marginalNote ? `<div class="mn">${esc(p.marginalNote)}</div>` : "";
      return `<div class="prov${amended ? " amended" : ""}" style="margin-left:${depth * 20}px">${mn}<div class="ptext"><span class="plabel">${esc(leaf(p))}</span>${esc(p.text)}</div></div>`;
    })
    .join("");

  const amendedBy = bill
    ? `as amended by Bill ${esc(bill.billNumber)} — ${esc(bill.title)}`
    : "as amended";

  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>${esc(delta.title)} — as amended</title><style>${PRINT_CSS}</style></head>
<body>
  <header class="doc-head">
    <div class="brand">INGENIUM <span>· BCF</span></div>
    <h1>${esc(delta.title)}</h1>
    <div class="cite">${esc(delta.citation)}</div>
    <div class="amended-by">${amendedBy}</div>
  </header>
  <main>${body}</main>
  <footer class="doc-foot">Generated by Ingenium — counsel review required · Confidential</footer>
  <script>window.onload=function(){setTimeout(function(){window.focus();window.print();},250)}</script>
</body></html>`;

  const w = window.open("", "_blank", "width=860,height=960");
  if (!w) return false;
  w.document.write(html);
  w.document.close();
  return true;
}

const PRINT_CSS = `
  * { box-sizing: border-box; }
  body { font: 13px/1.55 Georgia, "Times New Roman", serif; color: #1a1a1a; margin: 0; padding: 48px 56px; }
  .doc-head { border-bottom: 2px solid #1a2b4a; padding-bottom: 16px; margin-bottom: 24px; }
  .brand { font: 700 12px/1 ui-sans-serif, system-ui, sans-serif; letter-spacing: .14em; color: #1a2b4a; }
  .brand span { color: #9a7b2e; font-weight: 600; }
  .doc-head h1 { font-size: 22px; margin: 12px 0 4px; color: #111; }
  .cite { font-style: italic; color: #555; font-size: 12.5px; }
  .amended-by { margin-top: 8px; font: 600 12px/1.4 ui-sans-serif, system-ui, sans-serif; color: #9a7b2e; }
  main { margin-top: 8px; }
  .prov { margin: 0 0 12px; padding-left: 12px; border-left: 2px solid transparent; }
  .prov.amended { border-left-color: #c9a227; background: #fbf6e4; padding: 6px 12px; border-radius: 2px; }
  .mn { font: 700 11px/1.3 ui-sans-serif, system-ui, sans-serif; color: #333; margin-bottom: 2px; }
  .plabel { font-weight: 700; margin-right: 8px; }
  .doc-foot { margin-top: 40px; padding-top: 12px; border-top: 1px solid #ccc; font: 10px/1.4 ui-sans-serif, system-ui, sans-serif; color: #888; text-align: center; }
  @media print { body { padding: 0; } @page { margin: 22mm 18mm; } .prov.amended { background: #fbf6e4 !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
`;
