import type { ActProvision, ProvisionDelta } from "../types";

// Branded, client-side PDF of an Act "as amended" — built as an HTML document in
// a print window (no dependency, Vercel-safe). The updated Act = the delta's
// after-side: every row that isn't repealed, with added/changed rows marked.
const esc = (s: string) =>
  s.replace(/[&<>]/g, (c) => (c === "&" ? "&amp;" : c === "<" ? "&lt;" : "&gt;"));

const actName = (t: string) => t.replace(/\s*\([^)]*\)\s*$/, "");

function provHtml(p: ActProvision, amended: boolean): string {
  const mn = p.marginalNote ? `<div class="mn">${esc(p.marginalNote)}</div>` : "";
  return `<div class="prov${amended ? " amended" : ""}">${mn}<p><span class="lbl">${esc(
    p.label,
  )}</span> ${esc(p.text)}</p></div>`;
}

export function exportActPdf(delta: ProvisionDelta, billNumber: string, billTitle: string): boolean {
  const provs = (delta.rows ?? [])
    .filter((r) => r.status !== "repealed")
    .map((r) => ({ p: (r.after ?? r.before) as ActProvision | undefined, amended: r.status === "added" || r.status === "changed" }))
    .filter((x): x is { p: ActProvision; amended: boolean } => Boolean(x.p));
  const date = new Date().toLocaleDateString("en-CA", { year: "numeric", month: "long", day: "numeric" });
  const title = actName(delta.title);

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)} — as amended</title>
<style>
  @page { margin: 22mm 20mm; }
  * { box-sizing: border-box; }
  body { font-family: Georgia, "Times New Roman", serif; color: #16202e; line-height: 1.55; margin: 0; }
  .brandbar { display: flex; align-items: baseline; justify-content: space-between; border-bottom: 2px solid #16314f; padding-bottom: 8px; }
  .wordmark { font-weight: 700; font-size: 18px; letter-spacing: 0.08em; color: #16314f; }
  .brandsub { font-size: 10px; letter-spacing: 0.14em; text-transform: uppercase; color: #6b7280; }
  .titleblock { margin: 26px 0 22px; }
  .acttitle { font-size: 26px; font-weight: 700; color: #16314f; margin: 0 0 4px; }
  .cite { font-size: 12px; color: #6b7280; font-family: ui-monospace, Menlo, monospace; }
  .amendline { margin-top: 10px; font-size: 12.5px; }
  .amendline b { color: #16314f; }
  .prov { margin: 0 0 11px; }
  .prov p { margin: 0; font-size: 12.5px; text-align: justify; }
  .lbl { font-weight: 700; font-family: ui-monospace, Menlo, monospace; }
  .mn { font-style: italic; font-size: 11px; color: #6b7280; margin-bottom: 1px; }
  .prov.amended { border-left: 3px solid #c8a93a; padding-left: 10px; background: #fbf7e8; }
  .prov.amended .lbl::after { content: " · amended"; font-size: 8.5px; letter-spacing: 0.1em; text-transform: uppercase; color: #a98a1e; }
  .footer { margin-top: 28px; padding-top: 8px; border-top: 1px solid #d6dae1; font-size: 10px; color: #6b7280; display: flex; justify-content: space-between; }
</style></head>
<body>
  <div class="brandbar"><span class="wordmark">INGENIUM</span><span class="brandsub">Legislative Intelligence · BCF</span></div>
  <div class="titleblock">
    <h1 class="acttitle">${esc(title)}</h1>
    <div class="cite">${esc(delta.citation)}</div>
    <div class="amendline">As amended by <b>${esc(billNumber)}</b>${billTitle ? " — " + esc(billTitle) : ""}. Consolidated ${esc(date)}.</div>
  </div>
  ${provs.map((x) => provHtml(x.p, x.amended)).join("\n")}
  <div class="footer"><span>Generated by Ingenium — counsel review required before distribution.</span><span>Confidential</span></div>
</body></html>`;

  const w = window.open("", "_blank", "width=900,height=1100");
  if (!w) return false; // popup blocked
  w.document.open();
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 300); // let it lay out before the print dialog
  return true;
}
